# vim: nospell
language: minimal
sudo: required

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
    - env: GHC=7.8.4 CUDA=7.0-28 CABAL=1.18
      compiler: "GHC 7.8"
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.8.4
            - cabal-install-1.18
            - happy-1.19.5
            - alex-3.1.4

    - env: GHC=7.10.2 CUDA=7.0-28 CABAL=1.22
      compiler: "GHC 7.10"
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.10.2
            - cabal-install-1.22
            - happy-1.19.5
            - alex-3.1.4

  allow_failures:
    - env: CABAL=head GHC=head

before_install:
  - export PATH=/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH

  # Fetch stack
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://www.stackage.org/stack/linux-x86_64" | gunzip | tar -x
  - mv stack-*/stack $HOME/bin
  - ln -s stack-${GHC%.*}.yaml stack.yaml
  - travis_retry stack setup
  - |
      if [ ${GHC%.*} == 7.8 ]; then
        # required to install the 'cuda' package
        travis_retry sudo env PATH=$PATH stack --allow-different-user setup --upgrade-cabal || exit 1
        # GCE workers doesn't have enough space in /tmp to install ghc locally
        # via stack, so we need to install via apt and then --upgrade-cabal
        # using 'sudo'. This fixes the resulting permissions.
        sudo chown -R $USER:$USER $HOME/.stack || exit 1
      fi

  # Fetch CUDA
  - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_${CUDA}_amd64.deb
  - travis_retry sudo dpkg -i cuda-repo-ubuntu1204_${CUDA}_amd64.deb
  - travis_retry sudo apt-get update -qq
  - export CUDA_APT=${CUDA%-*}
  - export CUDA_APT=${CUDA_APT/./-}
  - travis_retry sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT}
  - travis_retry sudo apt-get clean
  - export CUDA_HOME=/usr/local/cuda-${CUDA%%-*}
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}

install:
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - opt --version; true
  - llc --version; true
  - travis_retry stack build --only-dependencies --no-terminal --no-haddock-deps -j2

script:
  - stack build --no-terminal --haddock --no-haddock-deps

notifications:
  slack:
    rooms:
      secure: "N8mahSWD81vtVqTB/xYMmCt27JO3hEz3AvnH5QaAhCLJkDmO/6Ijt6014sDEJ2s4TgW8+2jkP89cPqU7i/rzYZoVVwY9oyUq7rP6LkSdZ3rJ/fv1Yud/bTRFUAMxw13l/kV8SIFBh8UHYLlz2Hw/KRNPhTo1fFUrkrLlyLCR4Cg="

