#!/bin/bash

# Adjust to the installed location of ghci, if this script can not find it.
#
GHC=`which -a ghci | grep -v "\./ghci"`
VER=`$GHC --numeric-version`

# We assume that the dependent packages are install with 'cabal'. If you have
# installed them with another tool such as 'cabal-dev', add the following to the
# command.
#
#    -package-conf cabal-dev/packages-$VER.conf

# Also load the base Accelerate library. Assume that it is located in the parent
# directory, in the way the submodules are organised.
#
$GHC -i.. \
     -optP -include -optP dist/build/autogen/cabal_macros.h \
     -iutils \
     -Iinclude \
     -DACCELERATE_DEBUG \
     -DACCELERATE_BOUNDS_CHECKS \
     -DACCELERATE_INTERNAL_CHECKS \
     $@
