-- Helper script to shadow that automatically generated by cabal, but pointing
-- to our local development directory.
--

module Paths_accelerate_cuda where

import Data.Version
import System.Directory

version :: Version
version = Version {versionBranch = [0,14,0,0], versionTags = ["dev"]}

getDataDir :: IO FilePath
getDataDir = getCurrentDirectory

